### ISSUE TITLE
Modal submit not working

### ISSUE THREAD

**Issue by AEK-BKF** [JerseyMilker/Laravel-Bootstrap-Modal-Form#1]
Hi,
First, thank you so much for this nice package,
Please I follow your procedure to install it but submit button on modal not working :/ also errors don't appear on modal ..
Could you help me please ,,, Thanks

**Comment by jesseleite** [comment]
@AEK-BKF Thanks for kind words. Errors appear in my modals though. I'd have to see more info on versioning, and/or code samples, to help you pinpoint the issue.

**Comment by ghost** [comment]
@AEK-BKF I changed the first line from:
$('form.bootstrap-modal-form').on('submit', function(submission) {

to:
$(document).on('submit', 'form.bootstrap-modal-form', function(submission){

I don't know anything about jquery/ajax/php (I just tinker) but this seemed to work for me. Might help?

**Comment by chippy99** [comment]
Hi, thanks for creating this script it works very well once it is correctly setup. Initially the submit was not being prevented by the script and no validation occured but after much googling I found the answer.
The form open and close statements must be the first and last things in your modal, if you have any divs before or after form open/close statements it will not work. Hope this helps someone.

**Comment by RyanSMurphy** [comment]
Hi, 

I am closing this as there has been no action for a while on this ticket. If this is still an issue please raise another ticket with a code sample so I can test the code for myself.
