### ISSUE TITLE
Maintain Session Flash

### ISSUE THREAD

**Issue by tomhoad** [JerseyMilker/Laravel-Bootstrap-Modal-Form#3]
Great little script by the way - thanks very much.

Is there any way to maintain session flashes, like so:

```
Session::flash('status', "The event was created");
```

**Comment by RyanSMurphy** [comment]
Hi, is this still an issue?

**Comment by creativelink** [comment]
I'd also like to know how to add a confirmation. I can't send any flash back.

**Comment by mgralikowski** [comment]
My proposition.
Controller:
```
Flash::success(trans('system.saved_title'), trans('system.saved_msg'));
if ($request->wantsJson()) {
    return response()->json(['status' => 'ok']);
}
```
JS:
```
if (response.status == 'ok') {
    location.reload();
} else {
    alert('Unknown error! Please try again.');
}
```

I am using Szykra\Notifications\Flash (jquery pNotify) but you can use any library like this.
