### ISSUE TITLE
Anyone interested in maintaining this script?

### ISSUE THREAD

**Issue by jesseleite** [JerseyMilker/Laravel-Bootstrap-Modal-Form#7]
I'm not interested in maintaining this script any longer.  Is anyone interested in either taking over the repo, or maintaining a fork?  I could update my README to redirect to new author.

**Comment by RyanSMurphy** [comment]
@JesseLeite  I am interested in taking this from you. How do we go about giving me ownership of this and putting it under my name so I can effectively maintain this?

**Comment by jesseleite** [comment]
Hey @RyanSMurphy, thank you for reply!  It seems I cannot transfer as you already own a fork with this name...

![screen shot 2016-09-19 at 9 23 14 am](https://cloud.githubusercontent.com/assets/5187394/18633510/a93c4e84-7e4a-11e6-96a7-fd3b6a89f7ff.png)

You'll need to delete your fork first.

**Comment by RyanSMurphy** [comment]
@JesseLeite Done pal

**Comment by jesseleite** [comment]
@RyanSMurphy You should have a transfer request now.  I think once you approve that, it's yours 👍

**Comment by RyanSMurphy** [comment]
@JesseLeite thanks and good luck buddy
