### ISSUE TITLE
The help-block is removed

### ISSUE THREAD

**Issue by BasConijn** [JerseyMilker/Laravel-Bootstrap-Modal-Form#9]
When placing an helpBlock in an dialog, it is removed when opening.
`BootForm::text('Password', 'password')->helpBlock('A strong password should be long and hard to guess.')`

The BootForm documentation says this:

> Note: This help block will automatically be overridden by errors if there are validation errors.

However no help block is shown.

**Comment by RyanSMurphy** [comment]
Hi, is this still an issue?
